server:
  port: 80

spring:
  mvc:
    view:
      prefix: classpath:/templates
      suffix: .html
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    lettuce:
      shutdown-timeout: 1000
  thymeleaf:
    cash=false: false
  resources:
    static-locations: classpath:/static
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/blog?useUnicode=true&&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.aioe.test.demo.pojo
#  type-aliases-package:

logging:
  level:
    root: info
    com.aioe.test.demo: debug
  file:
    path: log/blog.log
  config:  classpath:logConfig/logback-spring.xml
